name: Sync encodings

on:
  schedule:
    - cron: "0 6 * * 1" # At 06:00 UTC on Monday

permissions: {} # Each job defines its own permissions explicitly

jobs:
  sync-encodings:
    name: Sync encodings
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up pnpm package manager
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Generate encodings if necessary
        run: pnpm generate-encodings

      - name: Format code with Oxfmt
        run: pnpm format

      - name: Open or update pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sync/encodings
          delete-branch: true
          add-paths: |
            encodings/*.json
            encodings/indexes.sha256
          commit-message: "chore: sync whatwg/encoding encodings"
          title: "chore: sync whatwg/encoding encodings"
          body: |
            ## Encodings updated

            The encodings in [whatwg/encoding/indexes.json] have been updated.

            ---
            *Auto-generated by the [sync workflow](.github/workflows/sync-encodings.yml).*
          labels: |
            automated
